doc/src/running-suites.rst

Auto restart is only restricted for no detach mode suites.
Doc change for cylc/cylc-flow#3184

Update auto restart restriction

---

doc/src/appendices/suiterc-config-ref.rst
doc/src/external-triggers.rst
doc/src/running-suites.rst
doc/src/suite-config.rst

Ported: https://github.com/cylc/cylc-flow/pull/3026
In our documentation, there is a 9.3.5.16 section titled "External Triggers". There is also an 11 section titled "External Triggers", with a named link to `External Triggers`.
It appears sphinx creates links with the section name, and that the link created for 9.3.5.16 External Triggers takes precedence over others. We can try right now browsing our documentation in the section 9.3.5.16, where it contains a link to the named link `External Triggers`. 
https://cylc.github.io/doc/built-sphinx-single/index.html#external-triggers (repair that the has anchor link has the name of the section, and Sphinx creates links in the same way).
I believe the intention was actually to link to the section 11 "External Triggers", and not to itself.
This …

Add an alias link for the External Triggers section

---

doc/src/appendices/appendices-master.rst
doc/src/appendices/install-file.rst
doc/src/appendices/readme-file.rst
doc/src/global-flow-conf.rst

When building the docs (as per the instructions in the ``README.md`` here) I get a few Sphinx warnings. I'm using ``Sphinx v2.0.1``, but the nature of the warnings mean they should appear for any version; they both arise because there are references for raw inclusion (via the ``literalinclude`` directive) of some files that are still in, & belong, in the ``cylc-flow`` directory, so are no longer in this repository (see also #20).
Fortunately, these are all minor &mostly unhelpful files, so are easy to deal with; no cross-repo referencing or duplication is required:
* ``INSTALL.md`` was very out of date (I will open an Issue to register this) & there is an Installation section for this anyway :arrow_right: remove the section which just prints it;
* ``README.md`` is viewable more accessibly …

Remove (now cross-repo) references to minor files

---

src/graphics/scale-images.sh

For the #29 PR I tried to run this script to have a matching image in the scaled directory, but it refused to work, and after some `echo`ing, it appears the value of the `PNG` variable had the directory structure too, resulting in 
```bash
(venv) kinow@kinow-VirtualBox:~/Development/python/workspace/cylc-doc/doc/src/graphics$ ./scale-images.sh
scaling png/orig/anatomy-of-a-job-script.png
convert-im6.q16: unable to open image `png/orig/png/orig/anatomy-of-a-job-script.png': No such file or directory @ error/blob.c/OpenBlob/2701.
convert-im6.q16: no images defined `png/scaled/png/orig/anatomy-of-a-job-script.png' @ error/convert.c/ConvertImageCommand/3258.
```
Cheers
Bruno

Fix scale-images script

---

src/ext/cylc_lang.py

Address syntax highlighting part of https://github.com/cylc/cylc-doc/pull/38#pullrequestreview-267514649.
Turns out that the `cylc_lang` extension in cylc-doc had got out of date with the one in rose.
The cylc-doc repository should be seen as the canonical location for Cylc Sphinx extensions. In the future we may remove it from Rose and find some way to import it from cylc-doc.

update cylc_lang extension

---

src/appendices/suiterc-config-ref.rst
src/external-triggers.rst
src/running-suites.rst
src/suite-config.rst
src/suite-design-guide/general-principles.rst
src/suite-design-guide/portable-suites.rst
src/suites/empy/cities/suite.rc
src/suites/inherit/single/one/suite.rc
src/suites/inherit/single/two/suite.rc
src/suites/integer-pipeline/suite.rc
src/suites/jinja2/cities/suite.rc
src/suites/jinja2/defaults/suite.rc
src/suites/message-triggers/suite.rc
src/suites/satellite/ext-trigger/suite.rc
src/suites/xtrigger/suite_state/downstream/suite.rc
src/suites/xtrigger/suite_state/upstream/suite.rc
src/suites/xtrigger/xrandom/suite.rc

Companion for cylc/cylc-flow#3191 - cycling and non-cycling suites now have
uniform level in the dependencies section.

Uniform dependencies section in suite.rc

---

src/ext/cylc_lang.py

Confirmed with @oliver-sanders already in #46 that this one can go :+1: and one review should do it.
This closes #46

Remove duplicate EmPy regex declaration

---

src/external-triggers.rst

What it says.  Ref: https://github.com/cylc/cylc-flow/pull/3258

Document xtrigger template escape.

---

setup.py

See https://github.com/cylc/cylc-flow/pull/3310#issue-310635758 where the exact same case applies here, except this time only one file (the ``setup.py`` again) in the repo had an old copyright notice.

Update copyright notice for setup script

---

src/external-triggers.rst

The built-in "custom" xtrigger ``echo`` is directly written out in the docs, & is now out of date, as the [actual xtrigger code](https://github.com/cylc/cylc-flow/blob/283bda1da40ee0d3baa14556000f4d6a4e3f4d43/cylc/flow/xtriggers/echo.py#L28-L29) (see also the [xtriggers directory equivalent](https://github.com/cylc/cylc-xtriggers/blob/a83eb011021cf67f96e79c14f4e003fa7d3f2ab8/cylc/flow/xtriggers/echo.py#L27-L28)) was updated from Python 2 to 3.
Ideally, instead of just updating the written-in code to match (actually, strictly I made it match the xtrigger repo version without the tuple parentheses in the return value, as they are not required), we could use a ``literalinclude:`` directive to add in the code itself, ensuring it will stay up-to-date, but I am not sure if that would be too …

Update echo xtrigger in line with current (Python 3) code

---

src/external-triggers.rst

Close #66.
Note that Sphinx will only create nested bullet points when there are blank lines separating the parent & child nesting levels, so in ``master`` there is a desired sub-list that has not been rendered as such, hence the included changes to the formatting.

Document Python versions xtriggers must be written in

---

src/appendices/suiterc-config-ref.rst
src/conf.py
src/introduction.rst
src/suite-config.rst
src/task-implementation.rst

Close #44. There are two components to this, where numbering has been removed for:
1. (as per the Issue to close) all figures as included via the ``figure:`` directive;
2. a small number of cases of code blocks numbered via 'Listing N' for some integer N, resulting from any use of the ``:caption:`` directive, which adds 'Listing N' before the stated text (e.g. ``Listing 1 input`` for ``:caption: input`` in a code block).
I have also (3) moved for ``suite.rc`` code with accompanying ``cylc graph`` output, the graph to the end rather than the start, as it seems more helpful & natural to show the code before showing the graph produced by it. It also means the caption is at the top, rather than in the middle, which had the potential to be slightly confusing.
Further context is provided below …

Remove numbering for listings w/ captions & figures

---

src/appendices/site-user-config-ref.rst

- remove documentation of obsolete `enable run directory housekeeping`
- update documentation of `run directory rolling archive length`
See:
- https://github.com/cylc/cylc-flow/issues/2732 
- https://github.com/cylc/cylc-flow/pull/3326

Remove obsolete run dir housekeeping docs.

---

src/appendices/site-user-config-ref.rst
src/task-job-submission.rst

The default assumes PBS 13 or newer. Companion of cylc/cylc-flow#3356.

Update PBS job name max len from 15 to 236

---

src/tutorial/runtime/introduction.rst
src/tutorial/scheduling/datetime-cycling.rst
src/tutorial/scheduling/graphing.rst
src/tutorial/scheduling/integer-cycling.rst

Tweaks to the tutorial resulting from the latest training session.
* Simplify ISO8601 mixed `:`/`-` warning
* Adjust bash shabang
* Change foo, bar, baz to a, b, c
* Clearer to non-programmers
* Clearer to non-native English speakers
* Change `purchase_ingredients` to `buy_ingredients`
* Clearer to non-native English speakers
* (note diddn't rename `consolidate_observations`, should we do this, typos in practicals sometimes help convey the text-processing nature of Cylc's configuration system)

Tutorial tweaks

---

Makefile
src/conf.py
src/tutorial/runtime/introduction.rst

Cause the Sphinx build to fail if any references are missing / corrupted. E.G. if you try to reference a python function which isn't documented you get an error.
This will be especially useful when we document more things like Cylc configurations etc.
This should fail until https://github.com/cylc/cylc-flow/pull/3417 is merged.

fail build on invalid references

---

src/installation.rst

Whilst this section will be re-written anyway we should make a note of our `coreutils` dependency.
Coreutils is required for basic functionality (e.g. the `timeout` command used within Cylc Flow) and optional functionality (e.g. the functional tests which use non-POSIX stuff like `sed -r`).
Note: We need Coreutils to be installed "as normal", e.g. on BSD it is safer to install commands with a prefix (e.g. `ls` => `gls`) to avoid conflict with the BSD equivalents. Typical workaround is to fudge it in the `.bashrc` file. Will add instructions for this when deployment is sorted.

document coreutuils dependency

---

src/suite-config.rst

Three commits, one uses `1..5` for parameter expansion. The examples appear to be related to a previous paragraph, where the docs use `1..5`, `ship, buoy, plane` for obs, etc. The examples match the content in that previous paragraph, except for this one, that is using 1..2.
The other commits were to align the multiline string in the examples. There is one example with multiline string that is aligned correctly, but the two subsequent examples appear to be off by a couple spaces?

Fix example in parameter expansion

---

src/suite-config.rst

*Result of recent user support*.
Cylc8 test PR: https://github.com/cylc/cylc-flow/pull/3448
Users can gain access to the Cylc logger from within Jinja2.
Should we encourage and document this?

jinja2: cylc logging

---

src/tutorial/scheduling/datetime-cycling.rst

Link to wikipedia broken. Suggested change: https://en.wikipedia.org/wiki/Nowcasting_(meteorology)

Attempt to fix broken link

---

src/glossary.rst

Corrects a backwards use of the word "trigger" in the glossary. Assigning @datamel as I found this when reading beyond the bounds of #105.  One review will do.

Minor doc tweak.

---

src/suites/inherit/single/two/suite.rc
src/user-guide/task-implementation.rst
src/user-guide/task-job-submission.rst
src/user-guide/writing-suites.rst

Since https://github.com/cylc/cylc-flow/pull/3653, references to these commands are no longer accurate.
Note there are still references to `jobscript` but these are still necessary as it is only the CLI command references that need removing, cylc still generates jobscripts.
I think this closes https://github.com/cylc/cylc-doc/issues/130, unless there are other commands I have missed! I also checked for references to cylc scp-transfer but none there.

Remove reference to cylc submit and jobscript CLI commands

---

.github/workflows/build-nightly.yml
.github/workflows/deploy.yml
.github/workflows/nightly.yml
Makefile
README.md
bin/set-default-path
bin/version
src/conf.py

Perform a nightly build of `cylc-doc:master` against `cylc-flow:master` at around 0:35UTC.
I've managed to jigger up GH actions on my own fork which is no longer recognising the `nightly` action so I've kinda deleted the evidence that this works, will try and get it going again, in the mean time take a look at my `gh-pages` branch:
https://oliver-sanders.github.io/cylc-doc/current/html/index.html
When we perform a new nightly build we delete the commit of the last one so that the branch history doesn't inflate massively.
Sadly this is a separate workflow from `deploy` as there is just too much different between the two to unify them in any meaningful way.

actions: nightly builds

---

.github/workflows/nightly.yml
.gitignore

The next nightly build will fail 😔.
This is because there will be conflicts on the `versions.json` file as I pushed up the docs for `7.8.6` and `7.9.1` today.
This PR re-generates the `version.json` file with each nightly build to overwrite any conflicts in the file.

Nightly rebase

---

.gitignore
doc/versions.js

Apply Ronnie's fix to make versions look nicer, already used on gh-pages.

 prevent versions from being word-wrapped

---

.github/workflows/nightly.yml

Nightly builds were supposed to be dropped from commit history, but weren't.
Problem was `git rebase -i --keep-base` wasn't getting any commits. Also need to force push.

Fix nightly build workflow

---

src/user-guide/running-suites.rst

* Restore the documentation for the `prev/next` ICP syntax which didn't get copied into the cylc-flow source code on account of being under its own section heading.
* Add a warning about setting the ICP relative to the current time when using eccentric calendars.

document: fix ingest time

---

setup.py

The sphinx_rtd_theme project either had a bug or made a bad design decision (not sure which) over the styling of definition lists, as of 0.5.0 it has been fixed/reverted.
This PR pins the version so we don't get that nasty styling again:
**Before:**
**After:**

setup: up sphinx_rtd_theme version

---

setup.py
src/conf.py

Sibling PR: https://github.com/cylc/cylc-sphinx-extensions/pull/32
The `hieroglyph_patch` extension is a dirty hack to get around this issue:
https://github.com/nyergler/hieroglyph/issues/148
But now that hieroglyph 2.1.0 has been released we no longer need it!
This removes the Sphinx version coupling which was locking us into an ever decreasingly small number of compatible Sphinx2 versions.

hieroglyph_patch: remove obsolete extension

---

.github/workflows/deploy.yml
.github/workflows/nightly.yml
.github/workflows/test.yml
.github/workflows/undeploy.yml

Fix test failures e.g. https://github.com/cylc/cylc-doc/pull/172/checks?check_run_id=1453710034
Do
```
- uses: actions/setup-node@v1
```
instead of
```
- uses: actions/setup-node@v1.4.2
```
because they update the tag `v1` to point to the latest `v1.x` release

GH Actions: Use looser actions version pinning

---

src/user-guide/writing-suites/parameterized-tasks.rst

This removes documentation of the "quirk" fixed by cylc/cylc-flow#3452
One review will do.

Remove out-of-date quirk doc.

---

src/installation.rst
src/suite-design-guide/general-principles.rst
src/suite-design-guide/portable-suites.rst
src/tutorial/furthertopics/retries.rst
src/tutorial/runtime/runtime-configuration.rst
src/user-guide/running-suites.rst
src/user-guide/task-implementation.rst
src/user-guide/task-job-submission.rst
src/user-guide/writing-suites/jinja2.rst
src/user-guide/writing-suites/runtime.rst

Some Platforms fixes for the documentation:
I have not assumed that every return from these commands is wrong, but as it happens, they were.
This is not an attempt to fix _every_ _single_ _issue_ in the docs, but to chip a chunk of the out-of-date material.
Given that I'm going to be on holiday I recommend that reviewers add/modify this PR using suggestions.

Basic platforms fix

---

src/tutorial/furthertopics/clock-triggered-tasks.rst

Should Close #61 
Questions:
- I'm I emphasizing that clock triggers are a special case of xtriggers (gateway). Good Idea?
- I don't go into specifics or much detail about `my_trigger = wall_clock(offset=PT0H):<ISOdatetime freq>`. Should I?

first go at revised clock-trigger tutorial

---

.github/workflows/nightly.yml

Had this idea after always having to update the URL of my ever-open nightly cylc-doc browser tab.
It's like how https://cylc.github.io/cylc-doc/current links to the latest version of the docs, but for the nightly builds, so that https://cylc.github.io/cylc-doc/nightly.latest links to the latest successful nightly build.

Add "nightly.latest" link

---

src/glossary.rst
src/suite-design-guide/general-principles.rst
src/user-guide/running-suites.rst
src/user-guide/writing-suites/configuration.rst

Just a quick initial update to the docs to include the file installation work. There will be more updates needed for rose-suite-run migration after symlink work is completed.

Initial file installation docs update

---

.github/workflows/deploy.yml
.github/workflows/nightly.yml
.github/workflows/test.yml
src/index.rst
src/installation.rst
src/plugins/cylc-rose.rst
src/plugins/index.rst

Sibling: https://github.com/cylc/cylc-rose/pull/22
Document the Cylc Rose plugin within the Cylc docs.
Options considered:
* Document in Rose (`metomi.github.io/rose`)
* Poor visibility.
* Cylc Rose is more of a plugin to Cylc than it is to Rose.
* Document in-place (`cylc.org/cylc-rose`)
* Poor visibility, won't appear in search results.
* Nice and simple.
* Document in Cylc (`cylc.org/cylc-doc`)
* Good visibility.
* There will be other Cylc plugins to document alongside.
Decided to try and document from the cylc.rose package docstring within cylc-doc.
Contains one un-related change to add a Sphinx reference label to the install docs so they can be easily referenced from other projects via intersphinx.

document cylc rose

---

bin/version

Nightly build had gone missing from version selector in bottom left corner

Fix missing nightly build in version links

---

.github/actions/install-dependencies/action.yml
.github/workflows/deploy.yml
.github/workflows/nightly.yml
.github/workflows/test.yml

Fix ``convert-im6.q16: unable to read font `helvetica'`` error on nightly & deploy workflows

Fix build failure and move apt install step to its own action

---

src/user-guide/running-suites.rst

Update documentation to include SSH task communication method.
Closes https://github.com/cylc/cylc-doc/issues/213
Also closes https://github.com/cylc/cylc-doc/issues/120

Update task communication documentation

---

cylc/doc/etc/tutorial/cylc-forecasting-suite/.validate
cylc/doc/etc/tutorial/runtime-introduction/.validate
src/glossary.rst
src/tutorial/furthertopics/broadcast.rst
src/tutorial/furthertopics/clock-triggered-tasks.rst
src/tutorial/furthertopics/message-triggers.rst
src/tutorial/furthertopics/queues.rst
src/tutorial/furthertopics/retries.rst
src/tutorial/furthertopics/suicide-triggers.rst
src/tutorial/runtime/introduction.rst
src/tutorial/runtime/runtime-configuration.rst
src/user-guide/running-suites.rst
src/user-guide/writing-suites/configuration.rst
src/user-guide/writing-suites/external-triggers.rst
src/user-guide/writing-suites/jinja2.rst

Update docs after https://github.com/cylc/cylc-flow/pull/4040 and https://github.com/cylc/cylc-flow/pull/4076
Question: the existing docs barely mention hold/release - should I add entries in the glossary for them? Update: yes, closes #53

Cylc play/pause

---

src/suite-design-guide/efficiency.rst
src/suites/inherit/multi/one/flow.cylc
src/suites/inherit/single/two/flow.cylc
src/tutorial/furthertopics/inheritance.rst
src/tutorial/runtime/configuration-consolidation/families.rst
src/tutorial/runtime/configuration-consolidation/index.rst
src/tutorial/runtime/configuration-consolidation/jinja2.rst
src/tutorial/runtime/configuration-consolidation/parameters.rst
src/tutorial/runtime/introduction.rst
src/tutorial/runtime/runtime-configuration.rst
src/tutorial/scheduling/graphing.rst
src/user-guide/writing-suites/configuration.rst
src/user-guide/writing-suites/jinja2.rst
src/user-guide/writing-suites/runtime.rst

Companion to https://github.com/cylc/cylc-flow/pull/4099

Unify get-config

---

.github/workflows/nightly.yml

The nightly build was failing on the step where it removes the previous nightly build.
See this fix in action: https://github.com/cylc/cylc-doc/runs/2217317677?check_suite_focus=true#step:11:1

Fix nightly build

---

src/glossary.rst

We've been playing with the word "flow" for long enough, time to get something solid down on paper so we can get on with the renaming and documentation.
Here are the terms in question (see also - https://github.com/cylc/cylc-flow/issues/3817#issuecomment-717206611):
* Workflow (run dir).
* Source Workflow (source dir or arbitrary location).
* Flow / Re-Flow.
* Workflow ID (i.e. registration).
> **Note:** Some glossary definitions missing, will fill these in once the "flow" terminology is agreed.

flow terminology

---

.gitignore
Makefile
src/_templates/docstring_only.rst
src/plugins/index.rst
src/plugins/install/index.rst
src/plugins/post-install/index.rst

Document the new `log_vc_info` post-install plugin (https://github.com/cylc/cylc-flow/pull/4142)

Autodocument post-install plugins

---

src/7-to-8/caveats.rst
src/7-to-8/cheat-sheet.rst
src/7-to-8/index.rst
src/7-to-8/major-changes/index.rst
src/7-to-8/major-changes/suicide-triggers.rst
src/7-to-8/summary.rst
src/index.rst

Addresses https://github.com/cylc/cylc-doc/issues/170
* move cylc 8 change overview into this section
* add a cheat sheet containing highlighted cli changes
* create a space for the "migration guide"
* write the first guide on suicide triggers to get the ball rolling

migration guide: add section for documenting cylc8 changes

---

src/user-guide/writing-workflows/runtime.rst

> **Built on:** #238
Correct documentation on valid task names patterns by documenting from the source code.

Document valid task names

---

.github/workflows/deploy.yml
.github/workflows/nightly.yml
.github/workflows/test.yml
.github/workflows/undeploy.yml

Closes #209 
Use `ubuntu-18.04` in GitHub Actions instead of latest so that the graphviz version we get isn't buggy. See https://github.com/cylc/cylc-doc/issues/209#issuecomment-853248945
I tested this using the nightly workflow and it worked (however, because the workflow ran as scheduled overnight using the master branch (with `ubuntu-latest`), it won't show up).

Fix overflowing diagrams

---

src/user-guide/writing-workflows/configuration.rst

Companion of https://github.com/cylc/cylc-flow/pull/4291

Remove references to obsolete "cylc edit" command.

---

src/glossary.rst
src/user-guide/running-workflows.rst
src/user-guide/writing-workflows/runtime.rst

Added a definition of "event handlers" to glossary. I'd have wanted it as a user.
Associated with https://github.com/cylc/cylc-flow/pull/4290

Glossary.event handlers

---

src/installation.rst

sibling: https://github.com/cylc/cylc-flow/pull/4296

portability: patch mac os dns issues

---

src/7-to-8/major-changes/cylc-install.rst
src/7-to-8/major-changes/platforms.rst
src/7-to-8/summary.rst

Partial response to https://github.com/cylc/cylc-doc/issues/170: Twinned with:https://github.com/cylc/cylc-rose/pull/68
- Added a Cylc install major changes page in the Cylc 8 migration guide.
- Added a link from the summary page to the major-changes/platforms page.

Major Changes - Cylc Install - Rose Stem

---

setup.py

Fixes bug documenting Cylc configurations caused by a nested section inside a meta section.

setup: bump cylc-sphinx-extensions to 1.3.1+

---

src/7-to-8/cheat-sheet.rst
src/7-to-8/major-changes/cylc-install.rst
src/installation.rst
src/plugins/cylc-rose.rst
src/user-guide/installing-workflows.rst

* update installation instructions *not* to use the meta package
* https://github.com/cylc/cylc-admin/issues/130
* update installation instructions
* document instaling the cylc-rose package

release: 8.0b2

---

src/user-guide/writing-workflows/jinja2.rst

Closes #215 
Deliberately not done:
Removed jinja2 references from documentation which should be template variable agnostic.

Document template vars

---

src/7-to-8/summary.rst
src/user-guide/writing-workflows/scheduling.rst

Doc changes for https://github.com/cylc/cylc-flow/pull/4457
[Additional] Noted the existence of compatibility mode in the 7-to-8 summary. 
tests will fail pending #304

TZ defaults to UTC at Cylc 8, unless compat_mode

---

.github/workflows/deploy.yml
.github/workflows/nightly.yml
.github/workflows/test.yml

Add cylc-uiserver to the build/test environment.
Required for #300

actions: add cylc-uiserver to build env

---

.github/workflows/deploy.yml
.github/workflows/nightly.yml

- Nightly build timing out
- Use new boolean type for workflow input - https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows/
- `if` condition in deploy workflow doesn't work as expected - https://github.com/actions/runner/issues/1483

GH Actions: Fix a couple of issues

---

src/user-guide/installing-workflows.rst

Reverts cylc/cylc-doc#302
Re-merge (or revert revert) after 8.0b3 docs deployed

Revert "No recursive installation"

---

.github/workflows/create-conda-envs.yml
setup.py

Discussed offline, `setuptools` version 49 breaks doc build due to changes in #342; but version 50 works.

Pin setuptools to >= 50.

---

src/hyperlinks.rst.include
src/index.rst
src/installation.rst
src/reference/environments/conda.rst
src/release-note.rst

I had a pending review of #342 that I forgot to finish off before it got trumped by other reviewers.
My main issue was:
> It's important to convey that although 8.0b3 is a still a "pre-release", it is now close enough to complete to be fully useable, with the disclaimer that it has not yet been heavily tested by users (although it has by us). Because, as recently reported on the forum, some sites are already facing new platforms without Python 2 available and our "not recommended for production use" messaging is putting them off Cylc 8.
I've attempted to strike a compromise that let's users decide if they want to take the risk, and that "Cylc 7 is stable and still available if needed".

Tweak release messaging.

---

src/reference/config/file-format.rst
src/reference/config/global.rst
src/reference/config/index.rst
src/reference/config/workflow.rst
src/tutorial/scheduling/graphing.rst
src/user-guide/writing-workflows/configuration.rst

Had a couple of new users confused about the file format. E.g., this was only documented in the tutorial:
>    We only use one set of square brackets at each level when writing nested sections on one line. But in the file, each nested sub-section gets a another set of square brackets as shown above.
So I added a new Reference section, and just referred out to that in the User Guide.
@wxtim may be some overlap with your tutorial rewrite (I just added a TODO comment to the tutorial docs here, since we haven't decided where that'll end up yet).

Tidy up file format documentation.

---

src/reference/config/writing-platform-configs.rst

Documents https://github.com/cylc/cylc-flow/pull/4534

platforms: document how to run jobs on a homeless platform.

---

404.html
etc/404.css
etc/404.js

Detects the version you tried to navigate to, offers a link to the docs homepage for that version. This is better than the current 404 page which offers no options.
To see a demo
- Go to https://metronnie.github.io/cylc-doc/8.0b3/html/7-to-8/index.html
- Try changing the version to 7.8.8 in the lower left sidebar
Note if you try entering an invalid version in the URL, it will only offer the link to the stable docs homepage

Create custom 404 page

---

src/_static/tutorial

This broken symlink appears to be making `test-tutorial-workflow` CI fail at its new home on cylc-flow

Delete broken tutorial symlink

---

Makefile
README.md
bin/c-locate
setup.py

Makes working with Sphinx much, much easier.
```console
$ make watch
```
Once you do this the docs will rebuild (incrementally where possible) whenever. Your browser will automatically refresh when this happens 🎉 😁 🥳 🕺!
There is also a `make watch-cylc` target which listens for changes in the `cylc-flow`, `cylc-uiserver` & `cylc-rose` repos. Note this performs a non-incremental build which is substantially slower.

make: Add sphinx-autobuild support

---

src/reference/config/writing-platform-configs.rst

Multiple top level headings will result in multiple contents entries.
Bumping this down a level so the contents contains a single entry "platform configuation" to match "workflow configuration", "uiserver configuration", etc.

fix heading levels

---

src/7-to-8/summary.rst
src/tutorial/furthertopics/broadcast.rst
src/tutorial/furthertopics/clock-triggered-tasks.rst
src/tutorial/furthertopics/family-triggers.rst
src/tutorial/furthertopics/index.rst
src/tutorial/furthertopics/inheritance.rst
src/tutorial/furthertopics/message-triggers.rst
src/tutorial/furthertopics/queues.rst
src/tutorial/furthertopics/retries.rst
src/user-guide/writing-workflows/scheduling.rst

Update the furthertopics tutorials for Cylc 8.
Similar to, but not actually overlapping #383

Fix additional tutorials

---

src/installation.rst

Sibling to https://github.com/cylc/cylc-flow/pull/4703
As soon as this is merged I will open a PR for 8.0rc2 that undoes this

Add note on markupsafe

---

src/7-to-8/caveats.rst
src/7-to-8/major-changes/cli.rst
src/7-to-8/major-changes/excluding-tasks.rst
src/7-to-8/summary.rst

Close #389
Document obsoleted `include/exclude at start-up` workflow config.
Also fixes a few typos and adds a 7-8 migration warning to check for use of the CLI in task scripting.

Improve back-compat info.

---

.github/workflows/test.yml
setup.cfg
src/installation.rst

No longer needed as we have pinned markupsafe to a max version in 8.0rc2.dev

Revert markupsafe thingies

---

src/conf.py

Fixes
```
Warning, treated as error:
/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/cylc/flow/network/client.py:docstring of
cylc.flow.network.client.WorkflowRuntimeClient::py:class reference target not found: zmq.asyncio.Context
make: *** [html] Error 2
Makefile:57: recipe for target 'html' failed
```
Better solution than https://github.com/cylc/cylc-flow/pull/4692 as it allows us to keep the type annotations
Sibling: https://github.com/cylc/cylc-flow/pull/4693 (but this needs merging first)

Fix build error due to intersphinx failing to find zmq class

---

src/tutorial/scheduling/graphing.rst

A trivial fix: table columns weren't side-by-side as intended.

Fix tutorial table formatting.

---

src/user-guide/task-implementation/job-scripts.rst

(I realise it's a little too big for comfort now, but can't seem to find a simple solution?)

Improve readability of diagram

---

.github/actions/create-conda-envs/action.yml
.github/actions/install-libs/action.yml
.github/workflows/deploy.yml
.github/workflows/nightly.yml
.github/workflows/test.yml
setup.cfg
src/_templates/versions.html
src/conf.py
src/reference/environments/envs/cylc-all.yml
src/reference/environments/envs/cylc-flow-anaconda.yml
src/reference/environments/envs/cylc-flow-base.yml
src/reference/environments/envs/cylc-flow-with-python.yml
src/reference/environments/envs/cylc-flow.yml
src/reference/environments/envs/cylc-rose.yml
src/reference/environments/envs/cylc-uiserver-with-traefik-proxy.yml
src/reference/environments/envs/cylc-uiserver-without-jupyterhub.yml
src/reference/environments/envs/cylc-uiserver.yml

Fix nightly builds and bring back `nightly.CCYY-MM-DD` version name in sidebar because it makes it more obvious you are looking at the nightly docs and we can more easily notice when the build is failing as the date becomes out-of-date.

Fix nightly

---

src/7-to-8/major-changes/python-2-3.rst
src/conf.py
src/glossary.rst
src/tutorial/runtime/runtime-configuration.rst
src/user-guide/writing-workflows/jinja2.rst

Add a major changes page covering Python changes which may need to be made during Cylc 7 -> 8 porting.
This is a list off the top of my head, can we think of anything else?

migration gude: python 2 => 3 implications

---

src/user-guide/writing-workflows/external-triggers.rst

* Sibling: https://github.com/cylc/cylc-flow/pull/4777
* Requires: https://github.com/cylc/cylc-doc/pull/422 (will fail until this is merged)

xtriggers: autodocument template variables

---

src/user-guide/writing-workflows/external-triggers.rst

I was asked whether Xtriggers were ready yet?

xtriggers: remove outdated adoption warning

---

src/7-to-8/summary.rst
src/glossary.rst
src/user-guide/running-workflows/scheduler-start-up.rst

Small documentation change to make it clear that file installation will be triggered upon `cylc reload`.
https://github.com/cylc/cylc-flow/pull/4797 (cylc -flow sibling)

Reload triggers remote file installation documentation

---

src/user-guide/running-workflows/scheduler-start-up.rst

Associated with https://github.com/cylc/cylc-flow/pull/4827
These docs were actually incorrect for `--final-cycle-point`, they were only correct for `--stop-cycle-point`. With this change, and after https://github.com/cylc/cylc-flow/pull/4827, they will be correct for both.

Update docs for `--fcp`/`--stopcp`

---

src/user-guide/writing-workflows/runtime.rst

- Removed OUTPUT event handler, which appears not supported.
- Reworded WARNING and EXCEPTION event handler descriptions.
- Added a not observing that CUSTOM event handlers are _only_ triggered
if the event severity is literally "CUSTOM".
Noticed this as a side effect of looking at https://github.com/cylc/cylc-flow/pull/4956

Tweaks to event handler documentation

---

src/tutorial/runtime/introduction.rst

Ensure consistency of use of `cylc get-resource` across tutorials.
Partially addresses https://github.com/cylc/cylc-doc/issues/470
Twinned with: 

small change to make usage of cylc get-resources consistent.

---

src/glossary.rst
src/user-guide/writing-workflows/scheduling.rst
src/workflow-design-guide/general-principles.rst

Goes with https://github.com/cylc/cylc-flow/pull/4906
Draft till I read through it myself, fix cross references, and check the build.

Update runahead limit documentation.

---

src/7-to-8/major-changes/compatibility-mode.rst
src/7-to-8/major-changes/scheduling.rst
src/7-to-8/major-changes/suicide-triggers.rst
src/7-to-8/summary.rst
src/glossary.rst
src/user-guide/running-workflows/reflow.rst
src/user-guide/running-workflows/tasks-jobs-ui.rst
src/user-guide/running-workflows/workflow-completion.rst
src/user-guide/writing-workflows/scheduling.rst

Terminology consistency tweak. (As discussed offline)
(Some extant doc PRs might need tweaking in the same way, now or post merge).

s/expected/required/g outputs.

---

src/7-to-8/major-changes/compatibility-mode.rst
src/7-to-8/major-changes/continuing-c7-c8.rst

Follow-up https://github.com/cylc/cylc-doc/pull/490#discussion_r922915976 
Many Cylc 7 workflows (at NIWA anyway!) "warm cycle" indefinitely, and cold-starting them is a last resort. 
E.g. our warm-cycled limited area atmos workflows can be cold started from global model data if absolutely necessary, but then forecast quality suffers over a subsequent spin-up period. 
Consequently, we can't just say "complete your run with Cylc 7". The best we can do is warn that that's preferred option *if possible*, and explain how to continue a run with Cylc 8, in a new run directory, if needed.

Document how to continue a Cylc 7 run with Cylc 8.

---

src/7-to-8/major-changes/config-changes.rst
src/user-guide/writing-workflows/configuration.rst
src/workflow-design-guide/style-guide.rst

Will only work with branch from https://github.com/cylc/cylc-flow/pull/4900

Document `cylc lint`

---

Makefile

* The `watch` builds were getting stuck in an infinite rebuild loop due
to changes in the dictionary directory at build time.

make: fix watch

---

.github/dependabot.yml
.github/workflows/create-conda-envs.yml
.github/workflows/deploy.yml
.github/workflows/nightly.yml
.github/workflows/test.yml
.github/workflows/undeploy.yml
setup.cfg

These changes fix pip dependency resolution timing out on GH Actions (caused by https://github.com/PyCQA/flake8/commit/975a3f45334861ebd8960c00e881443c23654bca)

Bump min python to 3.8

---

src/dictionaries/words
src/user-guide/writing-workflows/configuration.rst

Friend of https://github.com/cylc/cylc-flow/pull/5086

pyproject.toml: cylc lint settings

---

versions.json

This removes 8.0a2 from the sidebar (as the link is now dead).
The undeploy GH workflow didn't do this, I will try to fix that separately.

Remove 8.0a2 from `versions.json`

---

src/7-to-8/summary.rst
src/reference/config/file-format.rst
src/reference/config/shorthand.rst
src/tutorial/scheduling/graphing.rst

A user has complained thusly:
> This [upgrading to Cylc 8] isn’t as straightforward as it should be as: the WARNING message is written in a confusing shorthand; the ‘migration to cylc 8’ guide hasn’t told me where to find the document I need to understand the shorthand.
The shorthand referred to is:
```ini
[a cat]
[[a dog]]
[[[a fish]]]
```
gets written on one line as:
```ini
[a cat][a dog][a fish]
```
This PR adds a link from the migration guide to the file format documentation, and extends the documentation a bit.

7-to-8: Note config setting shorthand in validation warnings.

---

src/user-guide/sharing-access-to-workflows.rst

I think it's an underscore, not a hyphen, that must be used here? https://github.com/cylc/cylc-uiserver/blob/549afbd99389a5e29571b3f5f71cc6e4505a4270/cylc/uiserver/app.py#L170
Cheers
Bruno

Use underscore instead of hyphen for configuration

---

.github/actions/install-dependencies/action.yml
.github/workflows/deploy.yml
.github/workflows/nightly.yml
.github/workflows/test.yml
.github/workflows/undeploy.yml

`ubuntu-18.04` is now deprecated - https://github.com/actions/runner-images/issues/6002
Closes #247

GH Actions: upgrade to `ubuntu-latest`; use conda to install graphviz

---

.github/actions/install-dependencies/action.yml
.github/workflows/deploy.yml
.github/workflows/nightly.yml
.github/workflows/test.yml
src/dictionaries/words

With the change from `ubuntu-18.04` to `ubuntu-latest`, the `aspell` language dictionaries were no longer installed, so the spellchecker started using `hunspell` instead, which seemed to be falling back on `en_US` despite us setting `en_NZ`.

Fix spellcheck on GH Actions

---

src/user-guide/writing-workflows/external-triggers.rst

Closes #546 
From cylc.flow.xtrigger_mgr.TemplateVariables, not task_events_mgr.EventData
```
#!jinja2
[scheduler]
allow implicit tasks = True
[scheduling]
initial cycle point = 2781-03-21T02:17
[[graph]]
R1 = @my_trigger => foo
[[xtriggers]]
my_trigger = my_trigger(%({{VAR}})s)
```
```
def my_trigger(*args):
print(*args)
return (True, {})
```
Running script:
```
cylc install -n foo && cylc play foo -s 'VAR="uuid"'
```
Should return an exception for variables documented which are not actually available as xtrigger template variables such as `suite_uuid` and `uuid`.
Rebuilt docs available on my internal web space with alleged version 8.99.0.dev

Get list of template variables for xtriggers from correct place

---

src/tutorial/furthertopics/retries.rst
src/tutorial/runtime/runtime-configuration.rst
src/user-guide/running-workflows/retrying-tasks.rst
src/user-guide/writing-workflows/runtime.rst

Task state only goes to `failed` if there are no retries left.
Companion of https://github.com/cylc/cylc-flow/pull/5266

Document final retry behaviour.

---

.github/workflows/deploy.yml
.github/workflows/nightly.yml
.github/workflows/test.yml
src/reference/changes.rst

* There have been no functional changes to Rose 2.1 yet so we are skipping release.
* Remove this pin when we are ready to build against Rose master again.

actions: pin to metomi-rose 2.0.x

---

src/7-to-8/cheat-sheet.rst
src/glossary.rst

This is a basic addition of VR to the cheatsheet pending larger (and potentially more controversial) changes to the docs.
Served locally at `my-internal/domain/cylc-doc/8.1.1.dev/html/7-to-8/cheat-sheet.html`

Add vr to cheatsheet

---

bin/version

Follow-on to https://github.com/cylc/cylc-doc/pull/602, the nightly builds ran correctly, but aren't linked from the versions list because of the directory name change.

actions: fix nightly version links

---

README.md

This badge is now showing as "down" because the nightly builds are now based on the meta release versions. The version numbers will change so there is no longer a static link

Remove broken nightly link

---

src/dictionaries/words
src/user-guide/compound-commands.rst

Noticed that the compound commands page was missing the equivalent summary of VR to the one it has on VIP.

Added a description of VR to compound commands page

---

src/conf.py
src/hyperlinks.rst.include
src/user-guide/writing-workflows/jinja2.rst
src/workflow-design-guide/general-principles.rst

> It appears GitHub has made the Markdown renderer/file viewer require JavaScript which breaks linkcheck anchor checks.
https://github.com/sphinx-doc/sphinx/issues/11484

Fix linkcheck

---

src/7-to-8/major-changes/template-vars.rst
src/user-guide/writing-workflows/jinja2.rst

Companion of  https://github.com/cylc/cylc-flow/pull/5605

Added -z option

---

src/7-to-8/major-changes/ui.rst
src/conf.py
src/dictionaries/words
src/reference/architecture/ui-server.rst
src/reference/changes.rst
src/user-guide/sharing-access-to-workflows.rst
src/user-guide/task-implementation/job-scripts.rst

* Auto-spawning of other user's servers can now be configured.
* Jupyter Server security policy must be defined if Jupyter Lab or any other server extension is included in the deployment.
* Simplify some sections and expand on the new configurations.

cylc hub: document multi-user config post jupyter server v2 upgrade

---

src/workflow-design-guide/general-principles.rst

`UTC mode` only affects log timestamp time zone. The important setting is `cycle point time zone`, which is `Z` be default.

Update outdated UTC mode docs

---

src/user-guide/writing-workflows/empy.rst
src/user-guide/writing-workflows/jinja2.rst

- Close #622  (access to workflow files via templates)
- Document new workflow context variables https://github.com/cylc/cylc-flow/pull/5571

Update Jinja2 and EmPy templating sections.

---

src/conf.py
src/tutorial/runtime/runtime-configuration.rst
src/user-guide/installing-workflows.rst

Prep for course delivered October 2023.
Paired with changes in https://github.com/cylc/cylc-flow/pull/5744
- Clarify runtime tutorial
- Add a `cylc install` to the runtime tutorial.
- Fix broken Symlink
- Exempted `https://linux.die.net/.*` linkcheck tests. The domain seems to have implemented more stringent origin meta checks - [see comment on Element](https://matrix.to/#/!hwZqSYihGPuhDdIzIP:matrix.org/$169591864225544fzfBe:matrix.org?via=matrix.org)
IMO we should not merge these PR's until @joehickson and I have had a chance to skim the whole tutorial.

Fix.tutorial

---

.github/workflows/deploy.yml
.github/workflows/nightly.yml
.github/workflows/test.yml

The [hieroglyph library](https://github.com/nyergler/hieroglyph) is broken at the moment. This PR disables slide builds to work around this for now.

removed slides from builds until we have hieroglyph working again

---

src/user-guide/writing-workflows/scheduling.rst

I assume this is just left over from Cylc 7.

Remove outdated reference to warm start

---

.github/workflows/nightly.yml

We were checking out master even when we were supposed to be building 8.2.x.
Needs https://github.com/cylc/release-actions/pull/60
Demo: https://github.com/MetRonnie/cylc-doc/actions/runs/6666073608 - they each failed because I don't have a `gh-pages` branch on my fork, but the important thing is to look at what ref cylc-doc was checked out at

Nightly: checkout correct branch of cylc-doc

---

src/reference/changes.rst
src/user-guide/writing-workflows/external-triggers.rst
src/user-guide/writing-workflows/runtime.rst
src/user-guide/writing-workflows/scheduler.rst

companion to https://github.com/cylc/cylc-flow/pull/5727
I've had a look at the other uses of PYTHONPATH in the docs, and I think that they are safe.

added note about PYTHONPATH & CYLC_PYTHONPATH

---

src/7-to-8/cheat-sheet.rst

Paired with https://github.com/cylc/cylc-flow/pull/5838

Add cheat sheet entry on `rose date` -> `isodatetime`

---

src/reference/index.rst
src/tutorial/runtime/index.rst
src/tutorial/runtime/summary.rst
src/user-guide/index.rst
src/workflow-design-guide/index.rst

Action from washup at the end of a recent training session.
When presenting in person, we had a summary slide to help signpost useful resources, this jams it in at the end of the runtime tutorial, so that pressing "next" will take you to the summary page.

tutorial: add summary page

---

.gitignore
src/plugins/index.rst
src/plugins/xtriggers/index.rst
src/user-guide/writing-workflows/external-triggers.rst

I've attempted to add documentation for new functionality provided by https://github.com/cylc/cylc-flow/pull/5831. I hope it works properly. I think there should be a link between the external triggers documentation and the plugin documentation, but I'm not sure how to do that. Very specific advice would be appreciated.
When I tried to build this as myself I had issues and have not had time to try and debug, so I'm not sure how it renders (or if it is even valid).

Add documentation for xtriggers entry_point

---

src/dictionaries/words

Autodocumented exceptions introduced in #680 causing spellcheck to fail

Add words to spellcheck dictionary

---

src/user-guide/writing-workflows/scheduling.rst

Add a couple of labels so we can reference these sections from other places.

add reference labels

---

README.md

Copy Oliver's label advice from chat.

---

.gitignore
Makefile
bin/link-examples
src/user-guide/examples/index.rst
src/user-guide/index.rst

* Document the major design patters for implementing Cylc workflows.
* Along with https://github.com/cylc/cylc-flow/pull/5773, this closes #627
* Add some functional examples for users to play with.
* The aim is to help assist workflow writers by providing them with minimal templates to flush out.

user-guide: examples

---

src/user-guide/writing-workflows/configuration.rst

Accompanies https://github.com/cylc/cylc-flow/pull/5956
Deprecated `[cylc-lint]` in favour of `[tool.cylc.lint]` in `pyproject.toml`

Update docs for `cylc lint`

---

src/dictionaries/words

Fix [failing](https://github.com/cylc/cylc-doc/actions/runs/8522868514/job/23343967099) spell check on 8.2.x.

spelling: add subprocess to dictionary

---

src/index.rst
src/installation.rst
src/troubleshooting.rst

The beginnings of a Cylc 8 troubleshooting section, mostly aimed at users as opposed to sys-admins.
This is on an upstream branch, please contribute!
Specific troubleshooting for platform setup issues (sys-admin targetted content) is probably better placed in `src/reference/config/writing-platform-configs.rst`.

troubleshooting

---

src/reference/changes.rst
src/user-guide/writing-workflows/scheduling.rst

completion: add additional documentation

---

src/7-to-8/major-changes/compatibility-mode.rst
src/7-to-8/summary.rst
src/glossary.rst
src/user-guide/running-workflows/reflow.rst
src/user-guide/running-workflows/workflow-completion.rst
src/user-guide/task-implementation/job-scripts.rst
src/user-guide/writing-workflows/external-triggers.rst
src/user-guide/writing-workflows/runtime.rst
src/user-guide/writing-workflows/scheduling.rst
src/workflows/xtrigger/sequential/flow.cylc
src/workflows/xtrigger/workflow_state/downstream/flow.cylc

A quick blast through the docs (mostly the glossary) whilst trying not to overlap too much with the optional-outputs-extension, which should be documented separately (mostly by pasting from the proposal).
(I did add a glossary item on output completion, needed for cross-referencing).
We agreed not to define an "incomplete task" as **a finished task with incomplete outputs** (because that made "incomplete" different to "not complete" ). 
Now, "completion" is tied entirely to "output completion". That means it is legit to say that a task is incomplete if its outputs are incomplete, whether or not it has finished. That's convenient and I've used it a couple of times here. E.g. it means we can say a stall occurs if there is nothing left to run but *there are any incomplete tasks in the n=0 …

Some doc updates for 8.3.0.dev changes.

---

src/user-guide/task-implementation/job-submission.rst

Friend of https://github.com/metomi/rose/pull/2783
We shouldn't do anything to encourage using directives equivalent to execution time limit.

don't display bad practice

---

src/installation.rst

The man pages for FreeBSD on unix.com now redirect the community.unix.com?!
Found an alternative man page.

fix broken link

---

src/tutorial/furthertopics/broadcast.rst
src/tutorial/furthertopics/message-triggers.rst
src/user-guide/cheat-sheet.rst
src/user-guide/interventions/index.rst
src/user-guide/task-implementation/job-submission.rst

As flagged in Element chat, "whilst" is entirely equivalent to "while" in all uses here, but "whilst" sticks out as old-fashioned to many readers. We mostly use "while" in the docs, but a few "whilst"s have crept in.

whilst -> while

---

src/user-guide/writing-workflows/scheduling.rst

A topic which periodically comes up but is not presently documented.
See also: https://github.com/cylc/cylc-flow/issues/5729

document graph branching with multiple optional outputs

---

src/dictionaries/words

Spellcheck seems to be flagging a couple of words all of a sudden?!
Dunno, see this GH actions output: https://github.com/cylc/cylc-doc/actions/runs/12050889159/job/33600712776?pr=780#step:10:752

Add to dictionary

---

src/dictionaries/proper_nouns
src/installation.rst

Update installation docs

---

src/reference/job-script-vars/var-list.txt
src/workflow-design-guide/general-principles.rst

Companion of https://github.com/cylc/cylc-flow/pull/6117
`$CYLC_TASK_SHARE_CYCLE_DIR`

Updated docs about using ROSE_DATAC

---

src/conf.py
src/reference/changes.rst

* Sphinx tries to cross-link typing information.
* If it can't find a type to link to, it will fail in nit-pick mode.
* If we don't want it to fail, we must list the references in an ignore section.
Example failure: https://github.com/cylc/cylc-doc/actions/runs/13381697432/job/37371236269

fix build error

---

src/user-guide/writing-workflows/parameterized-tasks.rst

Tidy placement of admonition

---

src/glossary.rst
src/tutorial/furthertopics/retries.rst
src/tutorial/runtime/runtime-configuration.rst
src/user-guide/running-workflows/index.rst
src/user-guide/running-workflows/retrying-tasks.rst
src/user-guide/writing-workflows/runtime.rst

* Closes #570
* Merge the writing and running docs on retries to prevent sprawl (leave the old page in as a redirect).
* Clarify that retry delays are incremental.
* Add missing information about task events and triggers.
* Better inter-link the docs.

retries: consolidate and improve docs

---

src/7-to-8/major-changes/scheduling.rst
src/7-to-8/summary.rst
src/glossary.rst
src/reference/changes.rst
src/user-guide/interventions/index.rst
src/user-guide/running-workflows/reflow.rst
src/user-guide/running-workflows/tasks-jobs-ui.rst
src/user-guide/running-workflows/workflow-completion.rst
src/user-guide/task-implementation/skip-mode.rst
src/user-guide/troubleshooting.rst
src/user-guide/writing-workflows/runtime.rst
src/user-guide/writing-workflows/scheduling.rst
src/user-guide/writing-workflows/suicide-triggers.rst

(This branch is a few months old; it supersedes #798 which tried to be lighter weight but was still confusing).
Our overloading of the term "active" is still confusing:
- *"active tasks"* typically means tasks with active jobs
- (for historical reasons that don't really matter anymore)
- the *"active window"* (of the workflow) is the scheduler task pool 
- (task pool is no longer a user-facing term)
- the active window contains many tasks that are "not active"!
- the *`n=0` window* is identical to the "active window"
- (the latter term predates the former, but we kept both for reasons that don't really matter anymore)
- we now use the terms "active" and "inactive" internally, in scheduler code, to distinguish pool and future tasks
**This PR resolves the problem by dropping the redundant …

Disambiguate the word "active".

---

src/workflows/xtrigger/sequential/flow.cylc
src/workflows/xtrigger/workflow_state/downstream/flow.cylc

Fix [doc bug revealed on the forum](https://cylc.discourse.group/t/external-triggers-not-working-with-workflow-state-function/1143/2)
One review will do.

Fix example workflow_state xtrigger args.

---

src/user-guide/writing-workflows/scheduling.rst

#824 corrected the main runahead doc section to convey the current reality, that future tasks beyond the  runahead limit are not displayed as explicitly runahead limited - they just form the future graph. 
However, I didn't notice the examples below the text. 

Fix runahead limit documentation.

---

setup.cfg
src/conf.py

Add a copy button to code snippets.
I've wanted to do this for ages, but last time I looked this extension didn't exist. 
Built at https://████████████████/doc/cylc/8.5.2.dev/html/tutorial/scheduling/graphing.html#example

Add sphinx copybutton extension

---

.github/workflows/create-conda-envs.yml
.github/workflows/test.yml
src/installation.rst
src/reference/changes.rst

Update out-of-date info for 8.5

---

.github/workflows/create-conda-envs.yml
.github/workflows/deploy.yml
.github/workflows/nightly.yml
.github/workflows/test.yml
.github/workflows/undeploy.yml
bin/version
setup.cfg
src/installation.rst
src/lib/cylc_release.py
src/reference/changes.rst

Accompanies https://github.com/cylc/cylc-flow/pull/6809

Minimum Python 3.12

---

src/reference/changes.rst

changes: broadcast expiry
