doc/src/index.rst

Make all (sub-, etc) sections unnumbered

---

.travis.yml
setup.py
tox.ini

~**Built atop #26, merge after.**~
Run the pycodestyle linter over all Python code.

pycodestyle

---

src/task-job-submission.rst

Fix a typo reported on the Cylc Discourse forum.
One review will do.

Fix doc typo.

---

src/suite-config.rst

Companion of cylc/cylc-flow#3249.

Add ISODATETIMEREF and ISODATETIMECALENDAR to job script.

---

src/_static/css/slides-custom.css
src/api/zmq.rst
src/appendices/site-user-config-ref.rst
src/running-suites.rst

Should fix tests.
https://github.com/cylc/cylc-flow/pull/3254
One review should be sufficient.

update to move of cylc authorisation code

---

src/suite-name-reg.rst

Companion to https://github.com/cylc/cylc-flow/pull/3274

restrict suite name character set

---

src/appendices/suiterc-config-ref.rst
src/running-suites.rst

Companion of cylc/cylc-flow#3286

Remove redundant reference test related settings

---

src/external-triggers.rst

Document required format of xtrigger results dictionary

---

src/appendices/suiterc-config-ref.rst

Document more task event handlers args. See:
* cylc/cylc-flow#2458
* cylc/cylc-flow#2757
* cylc/cylc-flow#3325

Document more task event handler args

---

src/appendices/site-user-config-ref.rst
src/global-flow-conf.rst

Tiny tweak to go along with https://github.com/cylc/cylc-flow/pull/3375
One review will do.

Tweak docs on global config.

---

src/installation.rst
src/running-suites.rst

Doc companion of https://github.com/cylc/cylc-flow/pull/3377

Remove job-init-env.sh support.

---

src/appendices/site-user-config-ref.rst

Companion of cylc/cylc-flow#3402

Remove task message retry docs.

---

src/appendices/suiterc-config-ref.rst

un-deprecate runahead limit

---

src/task-implementation.rst

Close #87 
One review will do @dpmatthews

Document no message send retries.

---

src/img/recurrence-sections.svg
src/img/recurrence-sections2.svg
src/tutorial/scheduling/datetime-cycling.rst
src/tutorial/scheduling/integer-cycling.rst

Diagrams added to recurrence section to try and illustrate how it works.
Added `2/P2` to Recurrence Sections so that you can lead into it with the
consideration of the even numbers.

Added diagrams to the slide on recurrence

---

cylc/doc/etc/tutorial/message-trigger-tutorial/bin/random.sh
src/glossary.rst
src/tutorial/furthertopics/index.rst
src/tutorial/furthertopics/message-triggers.rst

Changed slightly from the original rose commit to clarify terminology.

Adding Message Trigger Tutorial to cylc-docs.

---

src/hyperlinks.rst.include
src/installation.rst
src/user-guide/running-suites.rst
src/user-guide/writing-suites.rst

Jot down the Mac OS installation instructions whilst they are fresh-ish in my head (will get re-jigged when we setup Mac OS testing on GH Actions).
Had a go at the installation instructions whilst I was at it. It's a first pass which will require more work but for the moment it's probably sufficient for alpha2.

installation: re-write

---

.github/workflows/deploy.yml
.github/workflows/test.yml

Allow the test workflow to be manually triggered (important for the cylc-flow release process).
Also tidy up subshells which aren't needed.

actions: manually trigger test workflow

---

src/user-guide/external-triggers.rst

Companion to https://github.com/cylc/cylc-flow/pull/3732.

validate xtrigger labels

---

.gitignore

Create gitignore on gh-pages branch

---

src/index.rst
src/introduction/architecture.rst
src/introduction/how-cylc-works.rst
src/introduction/index.rst

Tidy up the top-level sections of the docs by creating a new "introduction" section.

introduction

---

README.md

Re: #146 - I figure it can't hurt to have a badge for the nightly build status

Add nightly build workflow badge

---

src/installation.rst
src/tutorial/scheduling/graphing.rst
src/user-guide/running-suites.rst
src/user-guide/writing-suites.rst

Sister PR to https://github.com/cylc/cylc-flow/pull/3798
Small so 1 reviewer should be ok?

Deprecate [runtime][X][parameter environment templates]

---

src/user-guide/running-suites.rst

Adding authentication information to the docs.

Add authentication documentation

---

src/user-guide/task-implementation.rst

Sister PR to https://github.com/cylc/cylc-flow/pull/3820

Add note on task message validation

---

src/installation.rst
src/suite-design-guide/general-principles.rst
src/user-guide/task-job-submission.rst

Sister PR to https://github.com/cylc/cylc-flow/pull/3802 (although there isn't really any change in this, most of the doc updates were in that one)

Configuration file changes

---

.github/workflows/test.yml
src/reference/api/zmq.rst
src/reference/index.rst
src/suite-design-guide/general-principles.rst
src/suites/satellite/ext-trigger/flow.cylc
src/suites/xtrigger/xrandom/flow.cylc
src/tutorial/furthertopics/suicide-triggers.rst
src/user-guide/running-suites.rst
src/user-guide/writing-suites.rst

Make documentation reflect recent changes: 
- https://github.com/cylc/cylc-flow/pull/3846
- https://github.com/cylc/cylc-flow/pull/3844
- https://github.com/cylc/cylc-flow/pull/3848
And try to get the auto-build working again.

Fix.post mail changes

---

cylc/doc/etc/tutorial/consolidation-tutorial/flow.cylc
cylc/doc/etc/tutorial/cylc-forecasting-suite/.validate
cylc/doc/etc/tutorial/cylc-forecasting-suite/flow.cylc
cylc/doc/etc/tutorial/runtime-introduction/.validate
cylc/doc/etc/tutorial/runtime-introduction/flow.cylc
cylc/doc/etc/tutorial/runtime-tutorial/flow.cylc
src/user-guide/running-suites.rst
src/user-guide/task-job-submission.rst
src/user-guide/writing-suites/parameterized-tasks.rst
src/user-guide/writing-suites/scheduling.rst

Change a small number of links referring to config items which have been moved/renamed.
Partially closes_: https://github.com/cylc/cylc-flow/issues/3696

Config changes

---

.github/workflows/deploy.yml
.github/workflows/nightly.yml
.github/workflows/undeploy.yml
.github/workflows/update_copyright.yml
README.md
bin/autodoc-cli
bin/run-validate
bin/set-default-path
bin/version
cylc/doc/etc/tutorial/consolidation-tutorial/.validate
cylc/doc/etc/tutorial/cylc-forecasting-suite/.validate
cylc/doc/etc/tutorial/cylc-forecasting-suite/bin/consolidate-observations
cylc/doc/etc/tutorial/cylc-forecasting-suite/bin/forecast
cylc/doc/etc/tutorial/cylc-forecasting-suite/bin/get-observations
cylc/doc/etc/tutorial/cylc-forecasting-suite/bin/get-rainfall
cylc/doc/etc/tutorial/cylc-forecasting-suite/bin/post-process
cylc/doc/etc/tutorial/cylc-forecasting-suite/lib/python/mercator.py
cylc/doc/etc/tutorial/cylc-forecasting-suite/lib/python/util.py
cylc/doc/etc/tutorial/retries-tutorial/.validate
cylc/doc/etc/tutorial/runtime-introduction/.validate
setup.py
src/conf.py
src/ext/database_diagram.py

If we get this in before the new year, then we won't have to make any changes later.

Auto update copyright year

---

src/_static/css/custom.css
src/conf.py

Close #184
Tested in Chromium + Firefox

Fix missing logo

---

src/suites/jinja2/defaults/flow.cylc
src/user-guide/writing-suites/jinja2.rst

templatevars: document literal-eval parsing

---

.github/workflows/update_copyright.yml
src/conf.py

GH Actions: auto update copyright year in conf.py

---

src/glossary.rst
src/img/initial-start-stop-final-cp.svg
src/user-guide/running-suites.rst

Had to remind myself how start and stop cycle points work, wrote it down.

document the start and stop cycle points

---

Makefile
bin/set-default-path

Follow up to #193, fixes error:
> ```
> bin/set-default-path "doc/nightly" "nightly.2021-01-22" html ""
> bin/set-default-path: line 32: nightly.2021-01-22/index.html: No such file or directory
> ```

Fix nightly build

---

.github/workflows/deploy.yml
.github/workflows/test.yml
cylc/doc/etc/tutorial/cylc-forecasting-suite/.validate
cylc/doc/etc/tutorial/runtime-introduction/.validate
setup.py

actions: fix build

---

.github/workflows/test.yml

Make it easier to ensure that changes to documented projects don't cause docs build failures.

actions: enable changing the branch of documented projects in testing

---

src/installation.rst

sibling: https://github.com/cylc/cylc-flow/pull/4105

add sphinx label to wrapper script docs

---

.github/workflows/test.yml

Not sure how that happened, probably me rebasing in a hurry.

actions: fix workflow dispatch

---

src/glossary.rst

very small fix to link in glossary.

---

Makefile

Added new paths to auto-generated content introduced by #212
https://github.com/cylc/cylc-doc/blob/8088b4f2c8a603744b7b0c444e79f69c0ac6885e/.gitignore#L24-L26

Fix "make clean"

---

src/user-guide/installing-workflows.rst

Companion to https://github.com/cylc/cylc-flow/pull/4132

Configurable source dirs docs

---

Makefile
README.md

Demo: https://github.com/MetRonnie/cylc-doc/tree/readme#cylc-documentation

Add links to doc builds in readme

---

cylc/doc/etc/tutorial/cylc-forecasting-suite/bin/get-observations
cylc/doc/etc/tutorial/cylc-forecasting-suite/bin/get-rainfall

Looks like this variable was undocumented anyway which makes it easier.

deprecate CYLC_SUITE_DEF_PATH

---

src/user-guide/writing-suites/runtime.rst

Sibling to https://github.com/cylc/cylc-flow/pull/4177

Remove configurable work dir from global config

---

src/7-to-8/caveats.rst
src/glossary.rst
src/user-guide/running-workflows.rst

Twinned with cylc/cylc-flow#4238
Plus reword a couple of things to avoid confusion with cylc hold.
P.S. there isn't much mention of cylc hold in the docs, perhaps the tutorial could do with a cylc hold entry?

Update docs for cylc hold

---

src/7-to-8/major-changes/template-vars.rst
src/user-guide/writing-workflows/jinja2.rst

Related to https://github.com/cylc/cylc-doc/issues/170
Document the change to template vars.

migration guide: template variables

---

src/user-guide/writing-workflows/jinja2.rst

Fix small error in the text.

---

src/user-guide/writing-workflows/configuration.rst
src/user-guide/writing-workflows/runtime.rst
src/user-guide/writing-workflows/scheduling.rst
src/workflow-design-guide/efficiency.rst
src/workflows/empy/cities/flow.cylc
src/workflows/empy/cities/workflow-visualization.cylc
src/workflows/inherit/multi/one/flow.cylc
src/workflows/inherit/single/two/flow.cylc
src/workflows/jinja2/cities/flow.cylc
src/workflows/satellite/ext-trigger/flow.cylc

Sibling of https://github.com/cylc/cylc-flow/pull/4273

Remove obsoletion flow.cylc visualization section.

---

src/7-to-8/major-changes/platforms.rst
src/7-to-8/summary.rst
src/glossary.rst
src/user-guide/writing-workflows/configuration.rst

Add information on Platforms to docs

---

src/7-to-8/cheat-sheet.rst
src/tutorial/furthertopics/inheritance.rst
src/tutorial/runtime/configuration-consolidation/families.rst
src/tutorial/runtime/configuration-consolidation/index.rst
src/tutorial/runtime/configuration-consolidation/parameters.rst
src/user-guide/writing-workflows/runtime.rst
src/workflows/inherit/multi/one/flow.cylc

Update docs to match https://github.com/cylc/cylc-flow/pull/4275

config: make --sparse the default

---

src/index.rst

discourse badge

---

.github/workflows/test_tutorial_workflow.yml
cylc/doc/etc/tutorial/cylc-forecasting-workflow/lib/python/util.py
setup.py
src/ext/database_diagram.py
tox.ini

* Run the tutorial suite tests in another workflow.
* Move from pycodestyle -> flake8

actions: split test workflow

---

src/glossary.rst
src/user-guide/installing-workflows.rst
src/user-guide/running-workflows.rst
src/user-guide/writing-workflows/runtime.rst

Documentation for symlink dirs cli interface.
Build will fail until:
Cylc Flow related PR: https://github.com/cylc/cylc-flow/pull/4250/ has been approved and merged.

symlink dirs cli docs

---

src/tutorial/runtime/introduction.rst

companion to https://github.com/cylc/cylc-flow/pull/4389

move cylc.flow.processed

---

src/7-to-8/cheat-sheet.rst
src/7-to-8/major-changes/cylc-install.rst
src/7-to-8/summary.rst
src/user-guide/index.rst
src/user-guide/installing-workflows.rst
src/user-guide/removing-workflows.rst

Add docs for cylc clean

---

src/user-guide/writing-workflows/scheduling.rst
src/workflow-design-guide/style-guide.rst

Document https://github.com/cylc/cylc-flow/issues/4404

document graph line continuation on boolean

---

src/tutorial/scheduling/datetime-cycling.rst

Companion to https://github.com/cylc/cylc-flow/pull/4473

Companion.to.cylc.reviw

---

src/user-guide/sharing-access-to-workflows.rst

Tweak auth warning.

---

src/user-guide/running-workflows/running-workflows.rst

https://github.com/cylc/cylc-flow/pull/4521

companion to https://github.com/cylc/cylc-flow/pull/4521

---

src/user-guide/installing-workflows.rst

Ref https://github.com/cylc/cylc-flow/pull/4442

No recursive installation

---

src/7-to-8/cheat-sheet.rst
src/7-to-8/summary.rst
src/reference/architecture/data-flow.rst
src/tutorial/furthertopics/message-triggers.rst

I've been looking at adding a spell check step to the documentation build. 
I think that the list of words could be controversial, but this PR just contains uncontroversial spelling fixes since we're busy atm.

spelling fixes

---

src/glossary.rst
src/user-guide/introduction/note-on-examples.rst
src/user-guide/introduction/what-is-a-workflow.rst
src/user-guide/introduction/what-is-cylc.rst
src/user-guide/running-workflows/index.rst
src/user-guide/running-workflows/reflow.rst
src/user-guide/running-workflows/retrying-tasks.rst
src/user-guide/running-workflows/scheduler-start-up.rst
src/user-guide/running-workflows/task-job-states.rst
src/user-guide/running-workflows/tasks-jobs-ui.rst
src/user-guide/running-workflows/tracking-task-state.rst
src/user-guide/running-workflows/workflow-completion.rst
src/user-guide/writing-workflows/parameterized-tasks.rst
src/user-guide/writing-workflows/runtime.rst
src/user-guide/writing-workflows/scheduling.rst

Some final tweaks pre 8.0b3 release announcement. I'm going to merge this unilaterally but putting it up as a PR for visibility.

Final b3 doc tweaks

---

src/user-guide/installing-workflows.rst

Documentation for https://github.com/cylc/cylc-flow/pull/4526.

Disallow run n and run x as flow names

---

src/user-guide/running-workflows/scheduler-start-up.rst

These changes partially address https://github.com/cylc/cylc-flow/issues/4062
Companion to https://github.com/cylc/cylc-flow/pull/4543

Add docs for cycle point options in restart

---

src/user-guide/running-workflows/authentication-files.rst
src/user-guide/running-workflows/scheduler-start-up.rst

Reinstate + deconflict + tidy #320

Workflow config log files docs

---

cylc/doc/etc/tutorial/consolidation-tutorial/flow.cylc
cylc/doc/etc/tutorial/runtime-introduction/flow.cylc
cylc/doc/etc/tutorial/runtime-tutorial/flow.cylc

Leftover "belmullets" from https://github.com/cylc/cylc-doc/pull/265

belmullet → aldergrove

---

bin/version

Prevent 404.html from showing up in sidebar versions

---

src/user-guide/installing-workflows.rst

Companion to https://github.com/cylc/cylc-flow/pull/4549

Update notes about disallowed dir names in workflow name

---

src/user-guide/writing-workflows/runtime.rst

Caution note for platform select by subshell added.

---

src/7-to-8/cheat-sheet.rst
src/7-to-8/index.rst
src/7-to-8/major-changes/cli.rst
src/7-to-8/major-changes/compatibility-mode.rst
src/7-to-8/major-changes/cylc-install.rst
src/7-to-8/major-changes/play-pause-stop.rst
src/7-to-8/major-changes/suicide-triggers.rst
src/7-to-8/summary.rst
src/user-guide/writing-workflows/jinja2.rst
src/user-guide/writing-workflows/scheduling.rst

* Add some missing topics.
* Update to RC1 stuff.
* Try to reduce the bulk of some things.

728: migration guide

---

src/7-to-8/cheat-sheet.rst
src/7-to-8/major-changes/platforms.rst
src/reference/config/writing-platform-configs.rst

Sibling of https://github.com/cylc/cylc-flow/pull/4576

documentation for cylc config --platform-*

---

src/user-guide/running-workflows/simulation-modes.rst

Revise simulation modes doc.

---

.github/actions/install-dependencies/action.yml

https://github.com/pygraphviz/pygraphviz/issues/395

Workaround pygraphviz 1.8 bug for pip 22 / py 3.7

---

src/workflow-design-guide/style-guide.rst

Update script item style reccommendations

---

src/7-to-8/major-changes/play-pause-stop.rst
src/7-to-8/summary.rst
src/glossary.rst
src/reference/environments/conda.rst
src/user-guide/introduction/what-is-cylc.rst
src/user-guide/sharing-access-to-workflows.rst
src/user-guide/writing-workflows/configuration.rst
src/user-guide/writing-workflows/scheduling.rst

Very small spelling errors fix.

fix small spelling erros

---

src/7-to-8/major-changes/play-pause-stop.rst

Closes https://github.com/cylc/cylc-doc/issues/393

728: add instructions for re-running from scratch

---

src/7-to-8/caveats.rst
src/glossary.rst
src/reference/config/file-format.rst
src/tutorial/scheduling/datetime-cycling.rst
src/tutorial/scheduling/further-scheduling.rst
src/user-guide/task-implementation/job-submission.rst
src/user-guide/writing-workflows/scheduling.rst
src/workflow-design-guide/general-principles.rst
src/workflow-design-guide/portable-workflows.rst

I gave up on and closed #397 - these are the leftover spelling errors.

more spelling fixes

---

src/7-to-8/caveats.rst
src/user-guide/running-workflows/scheduler-start-up.rst

Improve reload docs + couple small fixes

---

src/reference/config/writing-platform-configs.rst

Couple of small RST issues and one re-wording.

fix small rst errors

---

setup.cfg

Having real fun deploying this one...
Temp patch, strip later.

setup: markupsafe

---

8.0rc1/html/reference/config/global.html

Error in the released rc1 code, fixing manually.
https://github.com/cylc/cylc-flow/pull/4722

hotfix 8.0rc1: fix error in global config

---

src/tutorial/runtime/configuration-consolidation/index.rst
src/tutorial/runtime/introduction.rst
src/tutorial/runtime/runtime-configuration.rst
src/tutorial/scheduling/datetime-cycling.rst
src/tutorial/scheduling/graphing.rst
src/tutorial/scheduling/integer-cycling.rst

Fixed a few problems I noticed with the slides whilst checking #418 : Mostly slides where content was
- Too wide
- Too long
- Overwhelming

Tidied the slides

---

src/reference/config/ui-server.rst
src/user-guide/sharing-access-to-workflows.rst

Fix UIS config path in docs.

---

.github/actions/create-conda-envs/action.yml
.github/workflows/create-conda-envs.yml
.github/workflows/deploy.yml

Actions: Fix create-conda-envs

---

src/user-guide/writing-workflows/configuration.rst

correct syntax instructions

---

CONTRIBUTING.md

https://github.com/cylc/cylc-doc/pull/438#issuecomment-1080393966

contributors: add shortlog comments

---

src/glossary.rst

* Closes https://github.com/cylc/cylc-doc/issues/442

glossary: prefer wallclock to wall-clock

---

.mailmap
CONTRIBUTING.md

CLA: Tomek Trzeciak

---

.mailmap
CONTRIBUTING.md

Close #445
- [ X] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.

Agree to CLA

---

src/installation.rst

Warn about non-virtual env installation.

---

src/installation.rst
src/tutorial/runtime/introduction.rst
src/tutorial/scheduling/datetime-cycling.rst

Add docs on optional dependencies

---

src/7-to-8/major-changes/compatibility-mode.rst
src/7-to-8/major-changes/config-changes.rst
src/7-to-8/summary.rst
src/tutorial/runtime/introduction.rst
src/tutorial/scheduling/graphing.rst
src/user-guide/installing-workflows.rst
src/user-guide/writing-workflows/scheduling.rst

Accompanies cylc/cylc-flow#4829

Update docs re: validation

---

src/7-to-8/major-changes/cylc-install.rst
src/conf.py
src/user-guide/installing-workflows.rst

Accompanies cylc/cylc-flow#4823

Update workflow installation docs

---

.github/workflows/deploy.yml

Increase deployment time limit?

---

src/7-to-8/major-changes/python-2-3.rst

Accompanies https://github.com/cylc/cylc-flow/pull/4877

Add note on Jinja2 zero-padded integers

---

CONTRIBUTING.md
src/tutorial/runtime/configuration-consolidation/parameters.rst
src/tutorial/scheduling/graphing.rst

I've updated the exercise code in the Parameters lesson, and corrected a small typo.

Tutorial material corrections

---

CONTRIBUTING.md
src/tutorial/runtime/introduction.rst

- [ x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
This addresses issue #482

Fix workflow ID inconsistency 

---

src/user-guide/writing-workflows/scheduler.rst

Sibling: https://github.com/cylc/cylc-flow/pull/4904
* Partially addresses https://github.com/cylc/cylc-flow/issues/4873.
* Clarify the FS requirements for workflow hosts.

auto restart: add note about enabling plugin

---

src/7-to-8/cheat-sheet.rst

Add reload advice to migration cheat sheet.

---

CONTRIBUTING.md
src/tutorial/furthertopics/clock-triggered-tasks.rst
src/tutorial/furthertopics/message-triggers.rst
src/tutorial/furthertopics/queues.rst
src/tutorial/runtime/configuration-consolidation/parameters.rst

Fix some small mistakes.

---

src/glossary.rst
src/tutorial/runtime/introduction.rst
src/user-guide/running-workflows/scheduler-log-files.rst
src/user-guide/running-workflows/scheduler-start-up.rst

Updates the docs with changes in light of https://github.com/cylc/cylc-flow/pull/4836.

log tidy changes

---

.github/actions/install-dependencies/action.yml
.github/workflows/deploy.yml
src/user-guide/writing-workflows/jinja2.rst

Small changes

---

src/workflow-design-guide/general-principles.rst

Fix some shell variable names.

---

src/user-guide/writing-workflows/scheduler.rst

Close #481 
Sibling of https://github.com/cylc/cylc-flow/pull/5003

Document abort meaning.

---

src/7-to-8/major-changes/remote-owner.rst
src/reference/config/writing-platform-configs.rst

Spelling corrections

---

src/user-guide/writing-workflows/scheduler.rst

clarify that run hosts should share a file system

---

src/reference/job-script-vars/var-list.txt

document CYLC_WORKFLOW_NAME_BASE

---

src/plugins/install/index.rst

Replaces https://github.com/cylc/cylc-flow/pull/4962

document the plugin api for pre_configure and post_install

---

src/7-to-8/major-changes/cylc-install.rst

728: improve rose suite-run migration docs

---

CONTRIBUTING.md

DS added as Contributor

---

src/reference/config/writing-platform-configs.rst
src/tutorial/runtime/runtime-configuration.rst
src/user-guide/sharing-access-to-workflows.rst

Small, one review should do.
Addresses https://github.com/cylc/cylc-doc/issues/515#issuecomment-1214959139.

Fix deprecation warnings for spelling

---

src/user-guide/writing-workflows/scheduler.rst

Accompanies https://github.com/cylc/cylc-flow/pull/5152

scheduler: document localhost platform

---

src/hyperlinks.rst.include
src/user-guide/writing-workflows/configuration.rst
src/user-guide/writing-workflows/empy.rst

fix broken links

---

src/7-to-8/major-changes/cylc-install.rst
src/user-guide/running-workflows/scheduler-start-up.rst

* To accompany https://github.com/cylc/cylc-flow/pull/5137

remote-install: document ana/ directory

---

README.md
src/tutorial/scheduling/datetime-cycling.rst

See https://github.com/cylc/cylc-flow/issues/5150

Fix tutorial example

---

src/dictionaries/proper_nouns
src/dictionaries/words
src/plugins/install/index.rst

Minor tweaks for spellcheck.

---

README.md
src/tutorial/furthertopics/retries.rst
src/tutorial/scheduling/datetime-cycling.rst
src/user-guide/sharing-access-to-workflows.rst
src/user-guide/writing-workflows/scheduler.rst

Cherry pick from master onto 8.0.x

---

.github/workflows/test.yml

GH Actions: Install correct branches of other libs

---

src/dictionaries/words
src/glossary.rst
src/tutorial/runtime/configuration-consolidation/index.rst
src/tutorial/runtime/configuration-consolidation/jinja2.rst
src/tutorial/runtime/configuration-consolidation/parameters.rst
src/user-guide/running-workflows/task-job-states.rst
src/user-guide/writing-workflows/parameterized-tasks.rst

remove alternative spellings of paramete?ri[sz]e

---

src/installation.rst

Document installing the Bash auto-completion script.

installation: document installing shell auto-completion

---

src/dictionaries/proper_nouns
src/user-guide/writing-workflows/scheduling.rst

Closes #367 & #455
May close #70 

added a note to explain hour placeholder in icp = next (T-??)

---

src/reference/changes.rst

added warning about incompatibility with Cylc 8.0.x with multiple flows

---

src/ext/database_diagram.py

flake8: ignore B028 rule in file

---

src/user-guide/running-workflows/task-job-states.rst

fix spelling

---

setup.cfg

Update sphinx-rtd-theme pin to avoid broken jQuery

---

README.md

readme: update deploy instructions

---

.github/workflows/nightly.yml

Fix endless pip backtracking for nightly

---

src/installation.rst

Document use of mamba to install Cylc.

---

src/conf.py
src/dictionaries/words
src/plugins/index.rst
src/plugins/job-runners/index.rst
src/user-guide/task-implementation/job-submission.rst

Revert "job runners: document handler interface"

---

src/dictionaries/words

spelling: add integrations

---

src/tutorial/furthertopics/message-triggers.rst
src/user-guide/running-workflows/scheduler-log-files.rst

Locally viewable at http://tims-server/cylc-doc/8.1.3.dev/html/index.html

detail using cylc message to add to scheduler log

---

src/7-to-8/major-changes/parameters.rst

A change that we forgot about which was recently noticed: https://github.com/cylc/cylc-flow/pull/3452

major changes: add parameter offsets page

---

src/user-guide/running-workflows/reflow.rst

Companion to https://github.com/cylc/cylc-flow/pull/5084

Update triggering docs for no active flows.

---

src/user-guide/writing-workflows/scheduling.rst

What it says.
Goes with https://github.com/cylc/cylc-flow/pull/5291

Update old-style clock-trigger warning.

---

CONTRIBUTING.md
src/user-guide/task-implementation/job-scripts.rst

fix set x typo

---

src/reference/job-script-vars/var-list.txt

Sibling: https://github.com/cylc/cylc-flow/pull/5560

job: document CYLC_TASK_DEPENDENCIES limit

---

src/user-guide/task-implementation/job-scripts.rst

One liner to accompany https://github.com/cylc/cylc-flow/pull/5606

remove duplicate index

---

src/user-guide/writing-workflows/parameterized-tasks.rst

Companion to https://github.com/cylc/cylc-flow/pull/5537

added documentation for <param><param2> syntax

---

src/glossary.rst
src/installation.rst
src/user-guide/task-implementation/job-scripts.rst
src/user-guide/writing-workflows/runtime.rst
src/user-guide/writing-workflows/scheduler.rst

Goes with https://github.com/cylc/cylc-flow/pull/5655

event handlers: improve docs

---

setup.cfg

Exclude broken sphinx version

---

setup.cfg
src/conf.py
src/ext/autodoc_traits/autodoc_traits.py
src/reference/config/ui-server.rst
src/user-guide/task-implementation/job-scripts.rst

https://github.com/sphinx-doc/sphinx/issues/11631
Depends on #625 for build to pass

Fix sphinx 7.2 build error

---

setup.cfg
src/conf.py

Requires https://github.com/metomi/rose/pull/2712

update intersphinx version

---

.github/actions/install-dependencies/action.yml

GH Actions: update setup-miniconda to v2.2.0

---

8.2.1/html/tutorial/runtime/runtime-configuration.html

* Manually apply https://github.com/cylc/cylc-doc/pull/653

fix tutorial

---

src/tutorial/runtime/runtime-configuration.rst

Small reword in tutorials

---

src/user-guide/writing-workflows/scheduling.rst

sequential tasks: remove deprecation phrasing

---

src/reference/job-script-vars/var-list.txt

Closes https://github.com/cylc/cylc-flow/issues/5764
See also 
https://github.com/cylc/cylc-flow/pull/5836

removed cylc_task_dep from var-list

---

src/dictionaries/words

dictionary: add cprofile

---

src/conf.py
src/reference/api/exceptions.rst
src/reference/api/index.rst

**Sibling:** https://github.com/cylc/cylc-flow/pull/5940
This turns on the napoleon extension for better formatting (it understands Google style docstrings) and the viewcode extension purely for fun.

api: document exceptions

---

src/user-guide/writing-workflows/scheduler.rst

improve workflow events documentation

---

.github/workflows/deploy.yml
.github/workflows/nightly.yml
.github/workflows/test.yml

Can we have this check on master so that I can make the comparison?
-  [x] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.

Actions: `pip list` on build failure for debugging

---

src/dictionaries/words
src/user-guide/writing-workflows/external-triggers.rst
src/workflows/xtrigger/sequential/flow.cylc

Relates to https://github.com/cylc/cylc-flow/pull/5738
Under _User Guide_ >> _Writing Workflows_ >> _External Triggers_ >> _Sequential Trigger Spawning_

Sequential trigger spawning

---

.gitignore
src/dictionaries/words
src/tutorial/runtime/runtime-configuration.rst
src/user-guide/running-workflows/scheduler-log-files.rst

Tutorial improvements/fixes

---

.github/workflows/test.yml
src/7-to-8/major-changes/cylc-install.rst
src/reference/config/writing-platform-configs.rst
src/user-guide/installing-workflows.rst

Add workaround for mirror/fcm make tasks conflicting with symlink dirs (cherry-pick from master)

---

.github/workflows/branch_sync.yml

GH Actions: fix invalid cron schedule

---

src/tutorial/scheduling/datetime-cycling.rst

Update outdated UTC mode paragraph

---

src/tutorial/furthertopics/inheritance.rst

Tiny fix requires single review IMO.

Small spelling fix

---

src/dictionaries/words
src/user-guide/writing-workflows/configuration.rst

Explain exactly what Jinja2 and shell code embedded in a `flow.cylc` means, and when/where it will be evaluated.

Explain code in flow.cylc files.

---

src/user-guide/writing-workflows/scheduling.rst

Docs for https://github.com/cylc/cylc-flow/pull/6046
So far this is only essential doc changes.

docs: submit-failed must be optional

---

.github/workflows/deploy.yml
.github/workflows/tims_docs.yml

Deply to wxtim docs

---

src/user-guide/task-implementation/job-scripts.rst
src/workflow-design-guide/general-principles.rst

Make it clearer that set -euo pipefail is _only_ required in

---

src/7-to-8/major-changes/cli.rst
src/user-guide/running-workflows/handling-job-preemption.rst
src/user-guide/running-workflows/retrying-tasks.rst

Closes the remainder of https://github.com/cylc/cylc-doc/issues/688

change set-outputs -> set

---

src/dictionaries/words

spelling: add vip to the dictionary

---

src/reference/changes.rst

Closes #633 
built copy at `~myserver/cylc-doc/8.3.0.dev/html/reference/changes.html`

Update Changelog links.

---

setup.cfg

workaround build errors with sphinx 7.4.4

---

src/tutorial/scheduling/integer-cycling.rst

tutorial: add allow implicit tasks into the diff context

---

src/conf.py

prevent example README files getting built

---

src/user-guide/writing-workflows/scheduling.rst

* Provide a single word (exclusion) to refer to the `!` syntax.
* Add an anchor to reference it.

combine exclusion sections

---

src/7-to-8/summary.rst
src/dictionaries/words
src/user-guide/running-workflows/scheduler-log-files.rst
src/user-guide/troubleshooting.rst

document workflow log files

---

src/7-to-8/summary.rst

Small expansion of Upgrade instructions.

expanded 7 upgrade instructions a little.

---

src/tutorial/furthertopics/clock-triggered-tasks.rst
src/tutorial/furthertopics/family-triggers.rst
src/tutorial/furthertopics/message-triggers.rst
src/tutorial/furthertopics/retries.rst
src/tutorial/runtime/configuration-consolidation/parameters.rst
src/tutorial/runtime/runtime-configuration.rst
src/tutorial/scheduling/datetime-cycling.rst

See also https://github.com/cylc/cylc-flow/pull/6454

remove UTC mode from tutorials

---

src/user-guide/running-workflows/advanced.rst
src/user-guide/running-workflows/index.rst

document cylc-flow#6438

---

src/user-guide/writing-workflows/configuration.rst

fix hyperlink

---

src/reference/config/writing-platform-configs.rst

Accompanies https://github.com/cylc/cylc-flow/pull/6168

Allow symlinking for log/job

---

src/reference/changes.rst
src/user-guide/cheat-sheet.rst
src/user-guide/interventions/index.rst
src/user-guide/running-workflows/retrying-tasks.rst

`cylc set` corrections

---

src/reference/changes.rst
src/user-guide/cheat-sheet.rst
src/user-guide/interventions/index.rst
src/user-guide/running-workflows/retrying-tasks.rst

#795 should've been on 8.4.x instead of master

Cherry-pick `cylc set` corrections

---

src/user-guide/interventions/index.rst

Accompanies https://github.com/cylc/cylc-flow/pull/6570

Update docs on `cylc set`

---

src/conf.py

Update nitpick ignore

---

src/user-guide/writing-workflows/scheduling.rst

Companion of https://github.com/cylc/cylc-flow/pull/6604
Closes https://github.com/cylc/cylc-doc/issues/699
A very quick fleshing out of the expiry docs.

examples: document expiry workflow design patterns

---

src/user-guide/interventions/index.rst

Use --wait instead of -wait

---

src/user-guide/running-workflows/tasks-jobs-ui.rst
src/user-guide/troubleshooting.rst

troubleshooting: flesh out the why are tasks waiting section

---

src/user-guide/writing-workflows/scheduling.rst

A recent user support request involved this pattern. It's not all that obvious how to hang tasks off the end of the chain so a worked example is a good idea here.
Please try this example out!

graph branching: add flaky pipeline example

---

src/user-guide/writing-workflows/runtime.rst

fix broken link

---

src/reference/config/shorthand.rst
src/tutorial/scheduling/graphing.rst

In response to feedback from training.

Clarify shorthand

---

src/user-guide/writing-workflows/scheduler.rst

Amend workflow events docs

---

CONTRIBUTING.md

Remove stray space in CONTRIBUTING.md

---

src/user-guide/writing-workflows/configuration.rst

Adds **Pulsar** (Atom continuation), **Helix** and **Zed**.  
I also moved Nano so that the list is ordered.

Add supported text editors to the list

---

src/user-guide/writing-workflows/scheduling.rst

@wxtim - this applies most of your suggestions (or variants thereof, at least) from #879 
Given that context, one review will do, then merge if you agree.
(I presume @oliver-sanders read the main PR and didn't have any major objections before merging it). 
Good for 8.6 if there's time, but no biggie.

Follow up review suggestions on #879
